import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from "@/app/LoginBtn";
import LogOutBtn from "@/app/LogOutBtn";
import {getServerSession} from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
   return (
    <html lang="en">
      <body>
        <div className="navbar">
          <div> <Link href="/" className="logo">Appleforum</Link> </div>
          <div> <Link href="/list">List</Link> </div>
          <div>
            {
              session !== null ?  <div>{session.user.name} <LogOutBtn /> </div> : <LoginBtn />
            }
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
