import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from "@/app/LoginBtn";
import LogOutBtn from "@/app/LogOutBtn";
import {getServerSession} from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
   return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          {
            session !== null ? <div> <div>{session.user.name}</div> <LogOutBtn /> </div> : <LoginBtn />
          }
        </div>
        {children}
      </body>
    </html>
  )
}
